import type { Metadata } from "next";
import { Inter, Fredoka, Cairo } from "next/font/google";
import "./globals.css";
import LanguageProvider from "@/components/LanguageProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// Fredoka — rounded & friendly: warm for young learners, still clean for parents
const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Cairo — friendly rounded Arabic; used for both headings & body when lang=ar
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ward Academy — Confident English, teacher-led & AI-supported",
  description:
    "Ward Academy helps young learners (ages 8–15) grow confident in English with original, level-matched practice — generated by AI, reviewed and approved by a real teacher. Book a free trial.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Arabic is the default; LanguageProvider updates lang/dir at runtime.
    <html
      lang="ar"
      dir="rtl"
      className={`${inter.variable} ${fredoka.variable} ${cairo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-cream text-ink">
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
